title: Nuno Marques # your name (or website title) here
logo: "/images/github%20portfolio%20picture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I’m a data analyst with a background in product and marketing management for video games, as well as market analysis/benchmarking.
I’ve helped game developers plan, validate, and execute their product and go-to-market strategy and defined, tracked and analysed market trends pre-development, and KPIs post-launch, to maximize opportunities for commercial and critical success.
My work in analysing social platforms, sales, and critical reception has led me to delve deeper into this branch of knowledge, to maximize value extracted from data and improve business and product decisions. I’m proficient at analysing and reporting on key project KPIs to upper management, as well as creating project dashboards to facilitate information flow and transparency throughout the organization. Additionally, I’m proficient at researching and analysing market niches to identify and advise on new product strategy avenues.
Do you want to employ analytical skills to ensure your organization is driven by sound and data-informed product and business strategy? Reach me through LinkedIn or my email nunomdmarques(at)gmail.com. 
  <br><br>
  <a href="https://www.linkedin.com/in/nuno-marques-267360120/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
