title: Nuno Marques # your name (or website title) here
logo: "https://raw.githubusercontent.com/nunomdmarques/nunomdmarques.github.io/master/images/github%20portfolio%20picture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/nuno-marques-267360120/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
